import type { AudioTelemetry, NonTechnicalAnalysis, VisionTelemetry } from "@/types/aiprep";

export function CommunicationAnalytics({ analysis, audio, vision }: { analysis: NonTechnicalAnalysis; audio: AudioTelemetry | null; vision: VisionTelemetry | null }) {
  const communication = [["Communication summary", analysis.communication_summary], ["Structure quality", analysis.structure_quality], ["Confidence notes", analysis.confidence_notes]].filter((item): item is [string, string] => typeof item[1] === "string");
  return <section className="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><h2 className="text-lg font-bold text-gray-900 dark:text-white">Communication and recording analytics</h2>{communication.length > 0 ? <dl className="mt-4 grid gap-4 sm:grid-cols-3">{communication.map(([label, value]) => <div key={label}><dt className="text-xs font-semibold uppercase tracking-wide text-gray-400">{label}</dt><dd className="mt-1 text-sm text-gray-700 dark:text-gray-200">{value}</dd></div>)}</dl> : <p className="mt-3 text-sm text-gray-500 dark:text-gray-400">Communication analysis is not available for this assessment.</p>}<Telemetry title="Audio analytics" values={audio ? [["Speaking pace", audio.speaking_pace_wpm], ["Filler words per minute", audio.filler_words_per_min], ["Silence ratio", audio.silence_ratio_pct], ["Average volume", audio.avg_volume_db], ["Background noise", audio.background_noise_level], ["Clipping detected", audio.clipping_detected ? "Yes" : "No"]] : null} unavailable="Audio analytics are not available for this assessment." /><Telemetry title="Video environment analytics" values={vision ? [["Face visible", vision.face_visible_pct], ["Head nods", vision.head_nods_count], ["Frame stability", vision.frame_stability_score]] : null} unavailable="Video analytics unavailable" /></section>;
}

function Telemetry({ title, values, unavailable }: { title: string; values: Array<[string, string | number]> | null; unavailable: string }) {
  return <div className="mt-5 border-t border-gray-100 pt-4 dark:border-gray-800"><h3 className="text-sm font-bold text-gray-900 dark:text-white">{title}</h3>{values ? <dl className="mt-3 grid gap-3 text-sm sm:grid-cols-3">{values.map(([label, value]) => <div key={label}><dt className="text-xs text-gray-400">{label}</dt><dd className="mt-1 font-semibold text-gray-800 dark:text-gray-100">{value}</dd></div>)}</dl> : <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">{unavailable}</p>}</div>;
}
